### ISSUE TITLE
"Add Client" age

### ISSUE THREAD

**Issue by rberntsen21** [stuininga/Capstone_FoodBankApp#37]
Age rounding up or not taking into account today's date, only the year (Make age an editable field after it pre populates from possibly.)

**Comment by stuininga** [comment]
Hmmm that was working when I last checked, I'll look at it again since it doesn't appear to be working right now. 

Age isn't be stored in the database since it's a calculable value, so it's literally just populating whenever the user enters anything, so there's not much point in it being editable.

**Comment by stuininga** [comment]
Age now populates based on the date properly.
